site_name: feiyan.help
site_url: https://feiyan.help
site_author: Chinese
site_description: Support the City of WuHan
copyright: Open source under GNU GPL v3.0

repo_name: feiyan.help
repo_url: https://github.com/wuhan-support/wuhan.support

nav:
  # 现状
  - 主页: index.md
  # 如何捐赠
  - 医护人员免费住宿:
    - 武汉大陆坊自如驿: hotels/dlfzry.md
  - 捐赠渠道:
    - 主要渠道: donate/index.md
    - 各个医院:
      - 华中科技大学同济医学院附属协和医院: donate/whuh.md
      - 武汉市中心医院: donate/chw.md
      - 武汉大学人民医院: donate/rmhwu.md
      - 武汉大学中南医院: donate/znhwu.md
      - 武汉市第一医院: donate/no.1hw.md
      - 武汉市儿童医院: donate/wch.md
      - 湖北省中医院: donate/whtc.md
  # 如何防护
  - 预防手册: protection/index.md
  # 如何就诊
  - 发热门诊定点机构:
    - 医院门诊: hospitals/index.md
    - 湖北省发热门诊定点机构: hospitals/hubei.md
    - 甘肃省发热门诊定点机构: hospitals/gansu.md
  # 与开发者沟通交流或者成为开发者
  - 贡献: 
      - 贡献: contribution/index.md
      - 贡献数据: contribution/data.md


theme:
  name: material
  language: 'zh'
  palette:
    primary: 'deep purple'
    accent: 'amber'
  logo: 'images/logo.png'
  feature:
    tabs: true
  font:
    text: 'Noto Sans'
    code: 'Cascadia Code'

extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/wuhan-support/'
  disqus: 'wuhan-support'

extra_css:
    - css/css.css
    #- css/extra.css

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

google_analytics:
  - 'UA-104387513-2'
  - 'auto'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      use_pygments: True
      noclasses: True
      pygments_style: monokai
  - def_list
  - footnotes
  - mdx_math
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: "#"

plugins:
  - search
  - awesome-pages
  # - git-committers
